export const CHANGE_FILTER_ROLE = 'CHANGE_FILTER_ROLE';
export const CHANGE_FILTER_STATUS = 'CHANGE_FILTER_STATUS';
export const CHANGE_SORT_NAME = 'CHANGE_SORT_NAME';
export const CHANGE_SORT_DATE = 'CHANGE_SORT_DATE';
export const ADD_EMPLOYEE = 'ADD_EMPLOYEE';
export const EDIT_EMPLOYEE = 'EDIT_EMPLOYEE';
export const DELETE_EMPLOYEE = 'DELETE_EMPLOYEE';
